#!/bin/bash

if [[ $# -ne 1 ]] && [[ $# -ne 2 ]]; then
  echo "Usage: $0 <filename_to_flash> <attacking>"
  exit 1
fi

BUILD_PATH=$1
ATTACKING=$2
# parent directory of update script
CI_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

power_cycle() {
  local USB_RETRY_COUNT=0
  /usr/sbin/uhubctl -l 1-1 -a cycle > /dev/null 2>/dev/null

  echo -n "Waiting for USB to connect"
  while [ ! -e "/dev/disk/by-label/DAPLINK" ]; do
    if [ "$USB_RETRY_COUNT" -gt  20 ]; then
      echo "%%FAILED%%\nReason: USB connection timeout"
      exit 47
    fi
    echo -n "."
    sleep 1
    ((USB_RETRY_COUNT++))
  done
  echo
}

FLASH_RETRY_COUNT=0
while true; do
  USB_RETRY_COUNT=0
  if [ "$FLASH_RETRY_COUNT" -gt 5 ]; then
    echo "%%FAILED%%\nReason: Flash max retries exceeded"
    exit 47
  fi
  echo "Putting board in update mode"
  python3 "${CI_DIR}/enable_update.py"
  power_cycle
  python3 "${CI_DIR}/disable_update.py"
  echo -e "Done!\nFlashing"

  python3 "${CI_DIR}/modified_flash.py" "$BUILD_PATH" /dev/ttyACM0
  if [ "$?" -ne 26 ]; then
    break
  fi
  ((FLASH_RETRY_COUNT++))
done

sleep 1

# attack board requires power cycle
if [[ -n "$ATTACKING" ]]; then
  echo "Power cycling board"
  power_cycle
  sleep 1
fi

echo "Testing with list"

LOGURU_LEVEL=INFO timeout 3s python -m ectf25.tv.list /dev/ttyACM0

if [ "$?" -ne 0 ]; then
  echo "%%FAILED%%\nReason: Listing failed."
  exit 47
else
  echo "Success!"
fi
