#!/bin/bash

if [[ $# -ne 1 ]] && [[ $# -ne 2 ]]; then
  echo "Usage: $0 <filename_to_flash> <attack_board>"
  exit 1
fi

BUILD_PATH=$1
ATTACK_BOARD=$2
# parent directory of update script
cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" || exit

FLASH_RETRY_COUNT=0
while true; do
  if [ "$FLASH_RETRY_COUNT" -gt 5 ]; then
    echo -e "%%FAILED%%\nReason: Flash max retries exceeded"
    exit 47
  fi
  echo "Putting board in update mode"
  python3 ./enable_update.py
  ./power_cycle.sh || exit $?
  python3 ./disable_update.py
  echo -e "Done!\nFlashing"

  python3 ./modified_flash.py "$BUILD_PATH" /dev/ttyACM0
  if [ "$?" -ne 26 ]; then
    break
  fi
  ((FLASH_RETRY_COUNT++))
done

sleep 1

# attack board requires power cycle
if [[ -n "$ATTACK_BOARD" ]]; then
  echo "Power cycling board"
  ./power_cycle.sh 1 || exit $?
else
  echo "Testing with list"
  timeout 3s python -m ectf25.tv.list /dev/ttyACM0
fi

if [ "$?" -ne 0 ]; then
  echo -e "%%FAILED%%\nReason: Listing failed."
  exit 47
else
  echo "Success!"
fi
